"""
Sweep every repo under ThePlace for PROSE text (wiki pages, READMEs, docs,
papers, addenda) — no code — strip to sentences, quality-gate out vendored /
generated / data-dump files, and ingest into ~/.ptolemy/monad_repos.bin to
deepen the Monad's vocabulary.

  python3 corpus_repos.py            -> corpus_repos.txt  (+ report on stderr)
  python3 corpus_repos.py --ingest   -> also learn into ~/.ptolemy/monad_repos.bin
"""
import os, re, sys, glob, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from corpus_strip import strip_file

ROOT = "/home/rendier/Projects/ThePlace"

# repos / dirs to sweep (Cody's own work). Skip venv-only / media-only dirs.
SKIP_TOP = {"lambeq_env", "__pycache__", "bins", "Pictures", "ContextPlease",
            "phone_pull_2026-06-06", "Music",
            "TheWanderingGod",   # personal-site archive: Wikipedia copies + forum dump, not project prose
            "Ptolemy2"}          # deprecated archive: third-party include/ libs + wordlists

# any path containing one of these segments is third-party / generated / data
SKIP_SEG = ("/.git/", "/.venv/", "/venv/", "/node_modules/", "/site-packages/",
            "/sourcebuilds/", "/technical/examples/", "/technical/sourcebuilds/",
            "/build/", "/dist/", "/htmlcov/", "/.pytest_cache/", "/__pycache__/",
            "/.mypy_cache/", "/.ruff_cache/", "/vendor/", "/third_party/",
            "/AddPapers/", "/references/", "/media/", "/datasets/", "/Datasets/",
            "/.ipynb_checkpoints/", "/archive/wiki_original/",
            "/content_wp/", "/content/", "/working/", "/dictionary/",
            "/include/", "/pdfstuff/", "/homeworks/", "/Phaleron/", "/Alexandria/")

# a file is rejected if its RAW text hits any of these
BAD_MARKERS = ("schema.org", "<!DOCTYPE", "<?xml", "This program is free software",
               "GNU GENERAL PUBLIC LICENSE", "Permission is hereby granted, free",
               "Qt Reference Documentation", "Generated by Doxygen",
               "Generated by Sphinx", "-----BEGIN", "Redistribution and use in source",
               "THE SOFTWARE IS PROVIDED", "npm ERR", "Traceback (most recent call last)")

_ALPHA = re.compile(r"[A-Za-z]")
_WORD  = re.compile(r"\b[a-z][a-z'-]{2,}\b", re.I)

def quality_ok(raw: str, prose: str) -> tuple:
    if len(prose) < 300:
        return False, "too short"
    low = raw[:8000].lower()
    for m in BAD_MARKERS:
        if m.lower() in low:
            return False, f"marker:{m[:20]}"
    lines = [l for l in prose.splitlines() if l.strip()]
    if not lines:
        return False, "empty"
    short = sum(1 for l in lines if len(l.split()) < 4)
    if short / len(lines) > 0.45:
        return False, "list/dump-like"
    onetok = sum(1 for l in lines if len(l.split()) == 1)
    if onetok / len(lines) > 0.30:
        return False, "wordlist-like"
    import statistics
    if statistics.median(len(l.split()) for l in lines) < 5:
        return False, "thin-lines"
    words = _WORD.findall(prose)
    if len(words) < 40:
        return False, "few words"
    # ratio of alpha chars to total non-space — reject symbol soup
    ns = [c for c in prose if not c.isspace()]
    if ns and sum(1 for c in ns if _ALPHA.match(c)) / len(ns) < 0.6:
        return False, "low alpha ratio"
    return True, "ok"

def gather():
    picked, rej = [], {}
    per_repo = {}
    for top in sorted(os.listdir(ROOT)):
        if top in SKIP_TOP:
            continue
        tp = os.path.join(ROOT, top)
        if not os.path.isdir(tp):
            continue
        files = []
        for ext in ("*.md", "*.txt", "*.rst"):
            files += glob.glob(os.path.join(tp, "**", ext), recursive=True)
        files = sorted(set(f for f in files if os.path.isfile(f)))
        n_ok = wc = 0
        for f in files:
            if any(seg in f for seg in SKIP_SEG):
                rej["skip-seg"] = rej.get("skip-seg", 0) + 1
                continue
            if os.path.getsize(f) > 3_000_000:      # >3 MB single text = a dump
                rej["huge"] = rej.get("huge", 0) + 1
                continue
            try:
                raw = open(f, encoding="utf-8", errors="replace").read()
            except Exception:
                continue
            prose = strip_file(f)
            ok, why = quality_ok(raw, prose)
            if not ok:
                rej[why] = rej.get(why, 0) + 1
                continue
            picked.append((f, prose))
            n_ok += 1
            wc += len(prose.split())
        if n_ok:
            per_repo[top] = (n_ok, wc)
    return picked, per_repo, rej

def main():
    picked, per_repo, rej = gather()
    out = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "corpus_repos.txt"), "w", encoding="utf-8")
    total = 0
    for _f, prose in picked:
        out.write(prose + "\n")
        total += len(prose.split())
    out.close()
    for repo, (n, w) in sorted(per_repo.items(), key=lambda x: -x[1][1]):
        sys.stderr.write(f"  {repo:28} {n:>4} files   {w:>9,} prose words\n")
    sys.stderr.write(f"\n  {len(picked)} files kept, {total:,} prose words\n")
    sys.stderr.write(f"  rejected: {dict(sorted(rej.items(), key=lambda x:-x[1]))}\n")

    if "--ingest" in sys.argv:
        sys.path.insert(0, "/home/rendier/Projects/ThePlace")
        from VAPMIP.monad import Engine
        e = Engine()
        text = open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                 "corpus_repos.txt"), encoding="utf-8").read()
        t0 = time.time(); n = 0
        for para in (p for p in text.split("\n") if p.strip()):
            n += e.crank.learn(para, weight=1.0)
        outb = os.path.expanduser("~/.ptolemy/monad_repos.bin")
        r = e.save_session(outb)
        sys.stderr.write(f"\n  ingested {n:,} words in {time.time()-t0:.1f}s\n")
        sys.stderr.write(f"  {r}   vocab {e.crank.n:,}   "
                         f"edges {sum(len(d) for d in e.crank._A):,}\n")

if __name__ == "__main__":
    main()
